spring:
  application:
    name: api
  h2:
    console:
      enabled: true
server:
  port: 9000

logging:
  level:
    root: error
    com :
      openclassrooms : INFO
    org :
      springframework :
        boot :
          autoconfigure :
            h2 : INFO
          web :
            embedded :
              tomcat : INFO
